version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      -"3000:3000"
    volumes:
      - /app/node_modules # Says do not try to map this container folder
      - .:/app # Map the current directory to the /app container folder
  tests: # Second container solely responsible for running tests
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"] # Override the default start command
    